<?php

namespace WebLoader\Test\Filter;

use WebLoader\Filter\PHPCoffeeScriptFilter;

/**
 * CompilerTest
 *
 * @author Jan Svantner
 */
class PHPCoffeeScriptFilterTest extends \PHPUnit_Framework_TestCase
{

	/** @var PHPCoffeeScriptFilter */
	private $object;

	protected function setUp()
	{
		$this->object = new PHPCoffeeScriptFilter();
	}

	public function testSimpleLoadAndParse()
	{
		if (!class_exists('CoffeeScript\Compiler')) {
			$this->markTestSkipped('Missing CoffeeScript compiler.');
		}

		$compiler = new PHPCoffeeScriptFilter();
		$coffee = $compiler->compileCoffee("number = -42 if opposite", null);

		$version = COFFEESCRIPT_VERSION;
		$expected = <<<COFFEE
// Generated by CoffeeScript PHP {$version}
(function() {
  var number;

  if (opposite) {
    number = -42;
  }

}).call(this);

COFFEE;
		$this->assertEquals($expected, $coffee);
	}
}
